# Generated by Django 5.1.2 on 2024-11-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_cart_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='restaurant_cart',
        ),
    ]
